### PR TITLE
new toolchain, legacy pmd rules

### PR DESCRIPTION
**Pull request by magwas**
See https://drive.google.com/file/d/1cbmgS-NfqZjVjw1U6DnCDex6qtfaavD1/view to understand what checks do we do, and how to make sure that your pull request is green.
(We do not do cpd, and your pmd rules are less picky.)

### CODE REVIEW

**Comment by grault** [comment]
Thanks for the video.. It was great, though I had difficulties following it locally, tools are not working. Would you like me to attempt fixing them?

( as a 1st problem, in tools/testenv you use docker without sudo; on RHEL distros, docker runs  through sudo[1], but you could make that a password-less experience by adding a line to /etc/sudoers, so I did that... next problem was that on my distro (CentOS btw, RHEL), I have a group id 10 which the docker process tries to add, already taken in the image, so it fails; then I stopped.. my next attempt would had been to get hold of the Dockerfile and try fixing that; ... or changing distros, which I don't really want )

I'll have a call today evening with Tamas, we'll probably discuss this as well.



[1] https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by magwas** [comment]
If you add yourself to the docker group, it will work. I should have mentioned it in the video.
And of course the group id of a person should not be one of the system users. You are not a uucp daemon.

**Comment by grault** [comment]
I'm not a uucp daemon indeed, but the testenv script gets the group ID from the HOSTING environment and not the container. It tries to use it in the CONTAINER though, which is I guess a different distro than I have, with uucp at 10.

I'm a wheel group member on my local box, so DEV_GID=$(id -g) assigns 10. This is an out-of-the-box CentOS with a single user being able to sudo.

Next. On an out-of-the-box CentOS, after installing docker (sudo yum install docker) there's no docker group at all. This distro uses root as the group for the docker socket[1], hence the need to sudo docker[1], but that's something I worked around already, with minor changes to the testenv script.

[1] https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by grault** [comment]
Anyhow, I'll try firing up the testenv based on the video when I'll have time. (this evening probably)

**Comment by grault** [comment]
Just fyi, the current problem which I'll probably solve by just installing an ubuntu on one of my VPSes: because of this RHEL approach grouping docker into root, all the docker mounts are owned by root/root, so "chown 1000:1000 /home/developer" fails w/ permission denied. I'll keep you updated.

**Pull request merged**
